---
title: "Quantitative Histories Workshop"
---

###### we link history, mathematics, and sociology to learn about in/justice and futurity.

### meet our team

| Nathan Alexander, PhD
- Assistant Professor, Howard University
- Founder of the Quantitative Histories Workshop
- Director of the Howard Community Data Fellowship

| Hye Ryeon Jang, PhD
- Assistant Professor, Morehouse College
- Director of the Morehouse Community Data Fellowship

| Kevin Bryson
- PhD student, University of Chicago
- Director of the Data Science and Critical Mathematics (DSCM) Program

| D'Juan James, MS
- Mathematics teacher, Butler Prep HS
- Assistant Director of the Data Science and Critical Mathematics (DSCM) Program

| Maya Phillips 
- Lab Manager and PostBacc
- BA, Spelman College


### meet our partners

| Center for Applied Data Science and Analytics (CADSA) 
- Amy Quarkume, PhD
-- Associate Professor, Howard University

| Spelman Census Center
- Celeste Lee, PhD, Assistant Professor
-- Spelman College

| 1526 Project
- Samuel Livingston, PhD
-- Associate Professor, Morehouse College


