---
title: ""
---

## Publications

### Books

Alexander, N. N. (2029). The Bard of the Potomac: An Autobiography of Kelly Miller. *Howard University Press*.

Alexander, N. N. (2028). Malcolm the Mathematician. *UNC Press*.

Alexander, N. N. (2027). Critical Data Science in K-12 Classrooms. *Teachers College Press*.

Alexander, N. N. (2026). Each One, Teach One: Supporting the Student Transition from Secondary Education to Postsecondary Mathematics. *Information Age Publishing*.

Alexander, N. N. (2025). Critical Thinking in K-6 Mathematics. *Open Educational Resources*.

Alexander, N. N. (2024). An Introduction to Critical Statistics. *Open Educational Resources*.

### Articles

## Case studies

### Data Wells
Get an introduction to our work on Ida B. Wells-Barnett here.

### Data and Du Bois
Get an introduction to our work on W. E. B. Du Bois here.

### Policing
Get an introduction to our `fatal force` analysis [here](fatalforce.html).

### Prisons
Get an introduction to our `prison` analysis here.

### The Quant Shop
Learn more about our forthcoming projects by visiting [The Quant Shop](https://github.com/quant-shop).

## Software, packages, and code

Check out some of the code I've written to support early researchers [here](https://rpubs.com/professornaite).

Check out a few software packages I created to conduct research on various issues.

- `critstats`

- `critbot`

