---
title: "Y'all be..."
description: ""
author: "Nathan Alexander, PhD"
date: "`r Sys.Date()`"
---

## Y'all be...

Y'all be homophobic. Y'all be classist. Y'all be abelist. And y'all be anti-Black.

Y'all be prioritizing neuro-typical traits in how you view people and their worth.

Y'all be throwing shade about the little things that people have no control over.

Y'all be mean spirited, and gossipy.

Y'all be ready to talk about systems but play in the face of folks who are impacted by those systems.

Like, y'all be lying - especially to people experiencing homelessness and housing insecurity.

Y'all be behind people's back talking but smiling in their face.

Y'all be hating.

Y'all be all the things...

## We be...

We be hating though.

We be standing by these watching folks play in other folks' faces.

We be lying; and we be lying to ourselves too.

We be the things you think we know but just aspire to be.

We be the hopeful yet we practice hopelessness.

We be citing on history while practicing ahistoricalness.

We be like y'all be:

We be transphobic. We be materialist. We be biased. We be anti-Black too.

We be helping but wanting to be seen.

We be a trip.

## Nostalgia

We be traveling in our minds to meet y'all.

We be thinking about the past.

We be meeting y'all.

When we be remembering y'all we write as a way to push back.

When we be finding y'all we talk but we don't act.

When we be with y'all we disagree but don't make it a big deal.

We be making comfortable routes for y'all as we keep quiet.

## Silence

We be silent.

We be using our previous experiences to defend how we act.

We be making excuses.

Y'all be making excuses.

We/You all be silent.

# Act

We act.

We act some more.
